// src/components/RecommendationList.jsx
import { useState, useMemo } from 'react';
import RecommendationCard from './RecommendationCard';
import ComparePanel from './ComparePanel';
import DestinationModal from './DestinationModal';

const SORT_OPTIONS = [
  { value: 'group_compatibility',    label: '⭐ Compatibility' },
  { value: 'average_rating',         label: '🌟 Rating' },
  { value: 'predicted_experience',   label: '🎯 Experience' },
  { value: 'budget_fit',             label: '💰 Budget Fit' },
  { value: 'sentiment_score',        label: '😊 Sentiment' },
  { value: 'seasonal_score',         label: '🌤 Seasonal Fit' },
];

const TYPE_FILTERS = ['All', 'Beach', 'Historical', 'Nature', 'Adventure', 'City'];

export default function RecommendationList({ recommendations, meta, onNavigate }) {
  const [sortBy, setSortBy]               = useState('group_compatibility');
  const [filterType, setFilterType]       = useState('All');
  const [filterBudget, setFilterBudget]   = useState('All');
  const [compareList, setCompareList]     = useState([]);
  const [showCompare, setShowCompare]     = useState(false);
  const [selectedDestination, setSelectedDestination] = useState(null);

  if (!recommendations || recommendations.length === 0) {
    return (
      <div className="empty-state-desktop">
        <div className="empty-icon">🔍</div>
        <div className="empty-title">No recommendations found</div>
        <div className="empty-desc">Try adjusting preferences or increasing the budget.</div>
      </div>
    );
  }

  // Quick picks
  const bestBudget = [...recommendations].sort((a, b) => b.budget_fit - a.budget_fit)[0];
  const bestRated  = [...recommendations].sort((a, b) => b.average_rating - a.average_rating)[0];
  const inSeason   = recommendations.find(r => r.in_peak_season);

  // Sort + filter
  const processed = useMemo(() => {
    let list = [...recommendations];
    if (filterType !== 'All') list = list.filter(r => r.destination_type === filterType);
    if (filterBudget === 'within') list = list.filter(r => r.budget_status === 'Within budget');
    if (filterBudget === 'above')  list = list.filter(r => r.budget_status === 'Above budget');
    list.sort((a, b) => (b[sortBy] ?? 0) - (a[sortBy] ?? 0));
    return list;
  }, [recommendations, sortBy, filterType, filterBudget]);

  const toggleCompare = (rec) => {
    setCompareList(prev => {
      const exists = prev.find(d => d.destination === rec.destination);
      if (exists) return prev.filter(d => d.destination !== rec.destination);
      if (prev.length >= 3) return prev;
      return [...prev, rec];
    });
    setShowCompare(true);
  };

  const exportTripPlan = () => {
    const lines = [
      '═══════════════════════════════════════════',
      '   PACKVOTE — GROUP TRIP RECOMMENDATIONS',
      '═══════════════════════════════════════════',
      `Travelers: ${meta?.total_travelers || 2} | Budget: ₹${meta?.budget_per_person || 5000}/night | Stay: ${meta?.accommodation_type || 'Hotel'}`,
      '',
      ...processed.map((r, i) => [
        `#${i + 1} ${r.destination} (${r.state}) [${r.destination_type}]`,
        `   Compatibility: ${r.group_compatibility.toFixed(1)}/100`,
        `   Rating: ${r.average_rating.toFixed(2)}/5 | Experience: ${r.predicted_experience?.toFixed(2) || '4.5'}/5`,
        `   Budget: ${r.budget_status} | Est. Cost: ₹${r.predicted_accommodation_cost?.toLocaleString('en-IN') ?? 'N/A'}`,
        `   Best Time: ${r.best_time}`,
        `   ${r.why_this_destination || ''}`,
        `   Spots: ${r.tourist_spots?.slice(0, 5).map(s => s.name).join(', ') || ''}`,
        '',
      ].join('\n')),
      '═══════════════════════════════════════════',
      'Generated by PACKVOTE — ML-Powered Travel',
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url;
    a.download = 'PACKVOTE_Trip_Plan.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="results-container-desktop">
      {/* ── Section 8: Top Destinations Header Row (32-38px title) ── */}
      <div className="results-header-bar">
        <div className="results-header-left">
          <h2 className="results-title-desktop">Top Destinations</h2>
          <p className="results-meta-desktop">
            {meta?.total_travelers || 2} traveller{meta?.total_travelers !== 1 ? 's' : ''} ·{' '}
            {meta?.budget_mode === 'total_trip' ? (
              <>₹{meta?.total_budget?.toLocaleString('en-IN')} overall budget (₹{meta?.budget_per_person?.toLocaleString('en-IN')}/night for {meta?.trip_days || 3}d) · </>
            ) : (
              <>₹{meta?.budget_per_person?.toLocaleString('en-IN')}/night stay budget ({meta?.trip_days || 3}d / {meta?.trip_nights || 2}n) · </>
            )}
            {meta?.accommodation_type || 'Hotel'}
          </p>
        </div>

        <div className="results-header-right">
          <span className="results-count-badge">{processed.length} RESULTS</span>
          {onNavigate && (
            <button className="btn-analytics-desktop" onClick={() => onNavigate('analytics')}>
              📊 View ML Charts
            </button>
          )}
          <button className="btn-export-plan-desktop" onClick={exportTripPlan}>
            📥 Export Trip Plan
          </button>
        </div>
      </div>

      {/* ── Section 9: Compact 3-Column Quick Picks Cards ── */}
      {(bestBudget || bestRated || inSeason) && (
        <div className="quick-picks-grid-desktop">
          {bestBudget && (
            <div
              className="quick-pick-card"
              onClick={() => setSelectedDestination(bestBudget)}
              title="Click to view details"
            >
              <div className="qp-card-label">💰 Best Budget</div>
              <div className="qp-card-title">{bestBudget.destination}</div>
              <div className="qp-card-meta">
                ₹{bestBudget.predicted_accommodation_cost != null ? bestBudget.predicted_accommodation_cost.toLocaleString('en-IN') : 'N/A'}/night · {bestBudget.budget_status}
              </div>
            </div>
          )}

          {bestRated && (
            <div
              className="quick-pick-card"
              onClick={() => setSelectedDestination(bestRated)}
              title="Click to view details"
            >
              <div className="qp-card-label">⭐ Highest Rated</div>
              <div className="qp-card-title">{bestRated.destination}</div>
              <div className="qp-card-meta">
                {bestRated.average_rating.toFixed(1)} / 5.0 Rating · {bestRated.state}
              </div>
            </div>
          )}

          {inSeason && (
            <div
              className="quick-pick-card"
              onClick={() => setSelectedDestination(inSeason)}
              title="Click to view details"
            >
              <div className="qp-card-label">🌤️ In Season Now</div>
              <div className="qp-card-title">{inSeason.destination}</div>
              <div className="qp-card-meta">
                Peak Window · {inSeason.best_time}
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── Sort & Filter Controls Bar ── */}
      <div className="sort-filter-toolbar">
        <div className="filter-group-item">
          <span className="filter-label-txt">SORT:</span>
          <select
            className="filter-select-input"
            value={sortBy}
            onChange={e => setSortBy(e.target.value)}
          >
            {SORT_OPTIONS.map(o => (
              <option key={o.value} value={o.value}>{o.label}</option>
            ))}
          </select>
        </div>

        <div className="filter-group-item">
          <span className="filter-label-txt">TYPE:</span>
          <div className="filter-chips-row">
            {TYPE_FILTERS.map(t => (
              <button
                key={t}
                type="button"
                className={`filter-chip-btn ${filterType === t ? 'active' : ''}`}
                onClick={() => setFilterType(t)}
              >
                {t}
              </button>
            ))}
          </div>
        </div>

        <div className="filter-group-item">
          <span className="filter-label-txt">BUDGET:</span>
          <div className="filter-chips-row">
            {[['All', 'All'], ['within', 'Within'], ['above', 'Over']].map(([val, lbl]) => (
              <button
                key={val}
                type="button"
                className={`filter-chip-btn ${filterBudget === val ? 'active' : ''}`}
                onClick={() => setFilterBudget(val)}
              >
                {lbl}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* ── Compare Panel ── */}
      {showCompare && compareList.length >= 2 && (
        <ComparePanel
          destinations={compareList}
          onRemove={d => setCompareList(prev => prev.filter(x => x.destination !== d.destination))}
          onClear={() => { setCompareList([]); setShowCompare(false); }}
        />
      )}

      {compareList.length === 1 && (
        <div className="compare-hint-bar">
          ℹ️ Select 1 more destination to compare side-by-side (max 3).
        </div>
      )}

      {/* ── Section 10: Destination Grid (3 cards/row at 1366px, 4 at 1920px) ── */}
      {processed.length === 0 ? (
        <div className="empty-state-desktop">
          <div className="empty-icon">🔍</div>
          <div className="empty-title">No destinations match filters</div>
          <div className="empty-desc">Try changing type or budget filter.</div>
        </div>
      ) : (
        <div className="destinations-grid-desktop">
          {processed.map((rec, i) => (
            <RecommendationCard
              key={`${rec.destination}-${i}`}
              rec={rec}
              meta={meta}
              delay={i * 0.05}
              isCompare={compareList.some(d => d.destination === rec.destination)}
              onToggleCompare={toggleCompare}
              onExplore={(r) => setSelectedDestination(r)}
            />
          ))}
        </div>
      )}

      {/* ── Complete Trip Plan Detail Modal ── */}
      {selectedDestination && (
        <DestinationModal
          destinationName={selectedDestination.destination || selectedDestination}
          recommendation={typeof selectedDestination === 'object' ? selectedDestination : null}
          onClose={() => setSelectedDestination(null)}
          onSelectDestination={(destName) => {
            const match = recommendations.find(
              (r) => r.destination.toLowerCase() === destName.toLowerCase()
            );
            setSelectedDestination(match || destName);
          }}
        />
      )}
    </div>
  );
}
